/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type InstructionStruct = { opcode: BigNumberish; args: BytesLike[] };

export type InstructionStructOutput = [opcode: bigint, args: string[]] & {
  opcode: bigint;
  args: string[];
};

export type QuantityStruct = { quantityType: BigNumberish; args: BytesLike[] };

export type QuantityStructOutput = [quantityType: bigint, args: string[]] & {
  quantityType: bigint;
  args: string[];
};

export type ProgramStruct = {
  config: BigNumberish;
  instructions: InstructionStruct[];
  quantities: QuantityStruct[];
};

export type ProgramStructOutput = [
  config: bigint,
  instructions: InstructionStructOutput[],
  quantities: QuantityStructOutput[]
] & {
  config: bigint;
  instructions: InstructionStructOutput[];
  quantities: QuantityStructOutput[];
};

export interface IBrevityInterpreterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "nonces"
      | "noop"
      | "run"
      | "runMeta"
      | "supportedConfigFlags"
      | "version"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "nonces", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "noop", values: [ProgramStruct]): string;
  encodeFunctionData(functionFragment: "run", values: [ProgramStruct]): string;
  encodeFunctionData(
    functionFragment: "runMeta",
    values: [ProgramStruct, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportedConfigFlags",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "version", values?: undefined): string;

  decodeFunctionResult(functionFragment: "nonces", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "noop", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "run", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "runMeta", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportedConfigFlags",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "version", data: BytesLike): Result;
}

export interface IBrevityInterpreter extends BaseContract {
  connect(runner?: ContractRunner | null): IBrevityInterpreter;
  waitForDeployment(): Promise<this>;

  interface: IBrevityInterpreterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  nonces: TypedContractMethod<[signer: AddressLike], [bigint], "view">;

  noop: TypedContractMethod<[p: ProgramStruct], [void], "payable">;

  run: TypedContractMethod<[p: ProgramStruct], [void], "payable">;

  runMeta: TypedContractMethod<
    [p: ProgramStruct, deadline: BigNumberish, sig: BytesLike],
    [void],
    "payable"
  >;

  supportedConfigFlags: TypedContractMethod<[], [bigint], "view">;

  version: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "nonces"
  ): TypedContractMethod<[signer: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "noop"
  ): TypedContractMethod<[p: ProgramStruct], [void], "payable">;
  getFunction(
    nameOrSignature: "run"
  ): TypedContractMethod<[p: ProgramStruct], [void], "payable">;
  getFunction(
    nameOrSignature: "runMeta"
  ): TypedContractMethod<
    [p: ProgramStruct, deadline: BigNumberish, sig: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "supportedConfigFlags"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "version"
  ): TypedContractMethod<[], [bigint], "view">;

  filters: {};
}
