/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as cloneFactorySol from "./CloneFactory.sol";
export type { cloneFactorySol };
import type * as test from "./test";
export type { test };
export type { BrevityInterpreter } from "./BrevityInterpreter";
export type { IBrevityInterpreter } from "./IBrevityInterpreter";
export type { OwnedBrevityInterpreter } from "./OwnedBrevityInterpreter";
