"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ISwap__factory = exports.Arb__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var Arb__factory_1 = require("./Arb__factory");
Object.defineProperty(exports, "Arb__factory", { enumerable: true, get: function () { return Arb__factory_1.Arb__factory; } });
var ISwap__factory_1 = require("./ISwap__factory");
Object.defineProperty(exports, "ISwap__factory", { enumerable: true, get: function () { return ISwap__factory_1.ISwap__factory; } });
