/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as arbSol from "./Arb.sol";
export type { arbSol };
export type { LoopTest } from "./LoopTest";
export type { MintableERC20 } from "./MintableERC20";
export type { Test } from "./Test";
export type { TestToken } from "./TestToken";
export type { TestTokenMultiMint } from "./TestTokenMultiMint";
