"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SetOwner__factory = exports.CloneFactory__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var CloneFactory__factory_1 = require("./CloneFactory__factory");
Object.defineProperty(exports, "CloneFactory__factory", { enumerable: true, get: function () { return CloneFactory__factory_1.CloneFactory__factory; } });
var SetOwner__factory_1 = require("./SetOwner__factory");
Object.defineProperty(exports, "SetOwner__factory", { enumerable: true, get: function () { return SetOwner__factory_1.SetOwner__factory; } });
