/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CloneFactory__factory } from "./CloneFactory__factory";
export { SetOwner__factory } from "./SetOwner__factory";
