/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  SetOwner,
  SetOwnerInterface,
} from "../../../contracts/CloneFactory.sol/SetOwner";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "owner_",
        type: "address",
      },
    ],
    name: "setOwner",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class SetOwner__factory {
  static readonly abi = _abi;
  static createInterface(): SetOwnerInterface {
    return new Interface(_abi) as SetOwnerInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): SetOwner {
    return new Contract(address, _abi, runner) as unknown as SetOwner;
  }
}
