/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  BrevityInterpreter,
  BrevityInterpreterInterface,
} from "../../contracts/BrevityInterpreter";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "currentNonce",
        type: "uint256",
      },
    ],
    name: "InvalidAccountNonce",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "signer",
        type: "address",
      },
    ],
    name: "nonces",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "config",
            type: "uint256",
          },
          {
            components: [
              {
                internalType: "uint256",
                name: "opcode",
                type: "uint256",
              },
              {
                internalType: "bytes32[]",
                name: "args",
                type: "bytes32[]",
              },
            ],
            internalType: "struct Instruction[]",
            name: "instructions",
            type: "tuple[]",
          },
          {
            components: [
              {
                internalType: "uint256",
                name: "quantityType",
                type: "uint256",
              },
              {
                internalType: "bytes32[]",
                name: "args",
                type: "bytes32[]",
              },
            ],
            internalType: "struct Quantity[]",
            name: "quantities",
            type: "tuple[]",
          },
        ],
        internalType: "struct Program",
        name: "p",
        type: "tuple",
      },
    ],
    name: "noop",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256[]",
        name: "mem",
        type: "uint256[]",
      },
      {
        internalType: "uint256",
        name: "from",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "to",
        type: "uint256",
      },
    ],
    name: "printMem",
    outputs: [],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "config",
            type: "uint256",
          },
          {
            components: [
              {
                internalType: "uint256",
                name: "opcode",
                type: "uint256",
              },
              {
                internalType: "bytes32[]",
                name: "args",
                type: "bytes32[]",
              },
            ],
            internalType: "struct Instruction[]",
            name: "instructions",
            type: "tuple[]",
          },
          {
            components: [
              {
                internalType: "uint256",
                name: "quantityType",
                type: "uint256",
              },
              {
                internalType: "bytes32[]",
                name: "args",
                type: "bytes32[]",
              },
            ],
            internalType: "struct Quantity[]",
            name: "quantities",
            type: "tuple[]",
          },
        ],
        internalType: "struct Program",
        name: "p",
        type: "tuple",
      },
    ],
    name: "run",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "config",
            type: "uint256",
          },
          {
            components: [
              {
                internalType: "uint256",
                name: "opcode",
                type: "uint256",
              },
              {
                internalType: "bytes32[]",
                name: "args",
                type: "bytes32[]",
              },
            ],
            internalType: "struct Instruction[]",
            name: "instructions",
            type: "tuple[]",
          },
          {
            components: [
              {
                internalType: "uint256",
                name: "quantityType",
                type: "uint256",
              },
              {
                internalType: "bytes32[]",
                name: "args",
                type: "bytes32[]",
              },
            ],
            internalType: "struct Quantity[]",
            name: "quantities",
            type: "tuple[]",
          },
        ],
        internalType: "struct Program",
        name: "p",
        type: "tuple",
      },
      {
        internalType: "uint256",
        name: "deadline",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "sig",
        type: "bytes",
      },
    ],
    name: "runMeta",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "supportedConfigFlags",
    outputs: [
      {
        internalType: "uint128",
        name: "",
        type: "uint128",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "version",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

export class BrevityInterpreter__factory {
  static readonly abi = _abi;
  static createInterface(): BrevityInterpreterInterface {
    return new Interface(_abi) as BrevityInterpreterInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): BrevityInterpreter {
    return new Contract(address, _abi, runner) as unknown as BrevityInterpreter;
  }
}
