"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.TestToken__factory = exports.TestCoin__factory = exports.Test__factory = exports.MintableERC20__factory = exports.LoopTest__factory = exports.arbSol = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.arbSol = __importStar(require("./Arb.sol"));
var LoopTest__factory_1 = require("./LoopTest__factory");
Object.defineProperty(exports, "LoopTest__factory", { enumerable: true, get: function () { return LoopTest__factory_1.LoopTest__factory; } });
var MintableERC20__factory_1 = require("./MintableERC20__factory");
Object.defineProperty(exports, "MintableERC20__factory", { enumerable: true, get: function () { return MintableERC20__factory_1.MintableERC20__factory; } });
var Test__factory_1 = require("./Test__factory");
Object.defineProperty(exports, "Test__factory", { enumerable: true, get: function () { return Test__factory_1.Test__factory; } });
var TestCoin__factory_1 = require("./TestCoin__factory");
Object.defineProperty(exports, "TestCoin__factory", { enumerable: true, get: function () { return TestCoin__factory_1.TestCoin__factory; } });
var TestToken__factory_1 = require("./TestToken__factory");
Object.defineProperty(exports, "TestToken__factory", { enumerable: true, get: function () { return TestToken__factory_1.TestToken__factory; } });
