"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.LoopTest__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
const ethers_1 = require("ethers");
const _abi = [
    {
        inputs: [
            {
                internalType: "int256",
                name: "n",
                type: "int256",
            },
        ],
        name: "loop",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
];
const _bytecode = "0x6080604052348015600f57600080fd5b5060a180601d6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c8063d61a2b6314602d575b600080fd5b603c60383660046053565b603e565b005b60005b81811215604f576001016041565b5050565b600060208284031215606457600080fd5b503591905056fea2646970667358221220f823cf0a5351bbfe9d60f216349f5c285b78c0e55c744628f7f9a441cb897db064736f6c634300081b0033";
const isSuperArgs = (xs) => xs.length > 1;
class LoopTest__factory extends ethers_1.ContractFactory {
    constructor(...args) {
        if (isSuperArgs(args)) {
            super(...args);
        }
        else {
            super(_abi, _bytecode, args[0]);
        }
    }
    getDeployTransaction(overrides) {
        return super.getDeployTransaction(overrides || {});
    }
    deploy(overrides) {
        return super.deploy(overrides || {});
    }
    connect(runner) {
        return super.connect(runner);
    }
    static createInterface() {
        return new ethers_1.Interface(_abi);
    }
    static connect(address, runner) {
        return new ethers_1.Contract(address, _abi, runner);
    }
}
exports.LoopTest__factory = LoopTest__factory;
LoopTest__factory.bytecode = _bytecode;
LoopTest__factory.abi = _abi;
